# theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
# title
title: GenSqlByCSV
description: The util to batch generate sql.
show_downloads: false
